# Generated by Django 6.0.4 on 2026-04-27 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_user_id', models.CharField(db_index=True, max_length=80)),
                ('policy_hash', models.CharField(db_index=True, max_length=64)),
                ('policy_preview', models.TextField(blank=True)),
                ('result_json', models.JSONField()),
                ('model_name', models.CharField(blank=True, max_length=120)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='profiles.profile')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
