# Generated by Django 6.0.4 on 2026-04-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_user_id', models.CharField(db_index=True, max_length=80)),
                ('name', models.CharField(max_length=80)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('employment_status', models.CharField(choices=[('student', 'student'), ('employed', 'employed'), ('unemployed', 'unemployed'), ('self-employed', 'self-employed'), ('retired', 'retired'), ('other', 'other')], max_length=30)),
                ('citizenship', models.CharField(blank=True, max_length=120, null=True)),
                ('housing', models.CharField(blank=True, max_length=120, null=True)),
                ('has_dependents', models.BooleanField(blank=True, null=True)),
                ('dependents_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('university', models.CharField(blank=True, max_length=120, null=True)),
                ('degree_level', models.CharField(blank=True, max_length=120, null=True)),
                ('financial_aid', models.CharField(blank=True, max_length=120, null=True)),
                ('industry', models.CharField(blank=True, max_length=120, null=True)),
                ('employment_type', models.CharField(blank=True, max_length=120, null=True)),
                ('income_bracket', models.CharField(blank=True, max_length=120, null=True)),
                ('business_type', models.CharField(blank=True, max_length=120, null=True)),
                ('num_employees', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
